//
// Created by mavros on 28/5/21.
//

#ifndef PROYECTOII_LETSPLAY_DIRECTION_H
#define PROYECTOII_LETSPLAY_DIRECTION_H

enum class direction {UP, DOWN, LEFT, RIGHT};

#endif //PROYECTOII_LETSPLAY_DIRECTION_H
